import { describe, expect, it } from "vitest";
import {
  AI_GENERATED_QUESTION,
  buildClassificationRequest,
} from "../lib/typesafe";

describe("buildClassificationRequest", () => {
  it("places tweet text in content and uses the required noul question", () => {
    expect(buildClassificationRequest("A sample tweet")).toEqual({
      state: { content: "A sample tweet" },
      questions: {
        aiGenerated: AI_GENERATED_QUESTION,
      },
    });
  });

  it("keeps the requested criteria wording", () => {
    expect(AI_GENERATED_QUESTION).toEqual({
      type: "noul",
      instructions:
        "Was the substantive wording of this text `content` generated by a generative AI system?",
      criteria: {
        true: "A generative AI system created or substantially rewrote the final text. This includes text where AI generated most of the wording, sentences, structure, or argument, even if a human later edited it.",
        false:
          "A human authored the substantive wording of the text. AI may have been used only for minor assistance such as spelling, grammar, punctuation, formatting, or small wording corrections without substantially rewriting the text.",
      },
    });
  });

  it("uses custom classification input when configured", () => {
    expect(
      buildClassificationRequest("A sample tweet", {
        customQuestion: "Is `content` an advertisement?",
        customYesCriteria: "The post promotes a product.",
        customNoCriteria: "The post does not promote a product.",
      }).questions.aiGenerated,
    ).toEqual({
      type: "noul",
      instructions: "Is `content` an advertisement?",
      criteria: {
        true: "The post promotes a product.",
        false: "The post does not promote a product.",
      },
    });
  });
});
