export type ConfidenceLevel = "low" | "medium" | "high";

export interface CustomClassificationSettings {
  customQuestion: string;
  customYesCriteria: string;
  customNoCriteria: string;
}

export interface ExtensionSettings extends CustomClassificationSettings {
  enabled: boolean;
  confidence: ConfidenceLevel;
  autoHide: boolean;
  showScores: boolean;
}

export const DEFAULT_CUSTOM_QUESTION =
  "Was the substantive wording of this text `content` generated by a generative AI system?";
export const DEFAULT_CUSTOM_YES_CRITERIA =
  "A generative AI system created or substantially rewrote the final text. This includes text where AI generated most of the wording, sentences, structure, or argument, even if a human later edited it.";
export const DEFAULT_CUSTOM_NO_CRITERIA =
  "A human authored the substantive wording of the text. AI may have been used only for minor assistance such as spelling, grammar, punctuation, formatting, or small wording corrections without substantially rewriting the text.";

export const DEFAULT_SETTINGS: ExtensionSettings = {
  enabled: true,
  confidence: "medium",
  autoHide: false,
  showScores: false,
  customQuestion: DEFAULT_CUSTOM_QUESTION,
  customYesCriteria: DEFAULT_CUSTOM_YES_CRITERIA,
  customNoCriteria: DEFAULT_CUSTOM_NO_CRITERIA,
};

export const CONFIDENCE_THRESHOLDS: Record<ConfidenceLevel, number> = {
  low: 0.3,
  medium: 0.5,
  high: 0.8,
};

export const API_KEY_STORAGE_KEY = "typesafeApiKey";
export const SETTINGS_STORAGE_KEY = "settings";
export const CONFIG_REVISION_STORAGE_KEY = "configRevision";

export function normalizeSettings(value: unknown): ExtensionSettings {
  if (!value || typeof value !== "object") return { ...DEFAULT_SETTINGS };

  const candidate = value as Partial<ExtensionSettings>;
  const confidence = isConfidenceLevel(candidate.confidence)
    ? candidate.confidence
    : DEFAULT_SETTINGS.confidence;

  return {
    enabled:
      typeof candidate.enabled === "boolean" ? candidate.enabled : DEFAULT_SETTINGS.enabled,
    confidence,
    autoHide:
      typeof candidate.autoHide === "boolean" ? candidate.autoHide : DEFAULT_SETTINGS.autoHide,
    showScores:
      typeof candidate.showScores === "boolean"
        ? candidate.showScores
        : DEFAULT_SETTINGS.showScores,
    customQuestion: normalizeCustomInput(candidate.customQuestion, DEFAULT_CUSTOM_QUESTION),
    customYesCriteria: normalizeCustomInput(
      candidate.customYesCriteria,
      DEFAULT_CUSTOM_YES_CRITERIA,
    ),
    customNoCriteria: normalizeCustomInput(
      candidate.customNoCriteria,
      DEFAULT_CUSTOM_NO_CRITERIA,
    ),
  };
}

export function isConfidenceLevel(value: unknown): value is ConfidenceLevel {
  return value === "low" || value === "medium" || value === "high";
}

function normalizeCustomInput(value: unknown, fallback: string): string {
  return typeof value === "string" ? value.slice(0, 2_000) : fallback;
}
